common: &common
  adapter: postgresql
  username: tocticket
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: tocticket_development

test: &test
  <<: *common
  database: tocticket_test

staging:
  <<: *common
  database: tocticket_staging

production:
  <<: *common
  database: tocticket_production

cucumber:
  <<: *test